# Dependencies
markdown:         redcarpet
highlighter:      rouge # Pygments

# Permalinks
permalink:        pretty # /posts/:title
# relative_permalinks: true

# Setup
title:            Kwritin
tagline:          'A coder blog'
description:      'Stay thinking, stay seeking.'
url:              http://toien.github.io
baseurl:          /
exclude:          ["node_modules"]
author:
  name:           'toien.L'
  url:            https://twitter.com/mdo

paginate:         5
gems:             ['jekyll-paginate', 'jekyll-gist']

# Custom vars
version:          0.0.1
env:              production # develop

github:
  repo:           https://github.com/toien/hyde
